[package]
name = "bridge-modules"
version = "1.0.0"
authors = []

[addresses]
atomic_bridge = "0x31a9bcd02c593c1e311e3edce7084f67397ea5b011aaefe650a2b700c0a5ea77"
moveth = "0x31a9bcd02c593c1e311e3edce7084f67397ea5b011aaefe650a2b700c0a5ea77"
master_minter = "0x31a9bcd02c593c1e311e3edce7084f67397ea5b011aaefe650a2b700c0a5ea77"
minter = "0x31a9bcd02c593c1e311e3edce7084f67397ea5b011aaefe650a2b700c0a5ea77"
admin = "0x31a9bcd02c593c1e311e3edce7084f67397ea5b011aaefe650a2b700c0a5ea77"
pauser = "0xdafe"
denylister = "0xcade"

[dev-addresses]
# moveth = "0xbeef"
# atomic_bridge = "0xfeef"
# master_minter = "0xbab"
# minter = "0xface"
# admin = "0xad"
# pauser = "_"
# denylister = "_"


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

