[package]
name = "ethereum-bridge"
description = "bridge components for the ethereum bridge"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
poem = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
aptos-api = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }

alloy = { workspace = true }
alloy-contract = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-signer-wallet = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-transport = { workspace = true }
alloy-transport-ws = { workspace = true }

bridge-shared = { workspace = true }
mcr-settlement-client = { workspace = true }

