services:
  setup:
    image: ghcr.io/movementlabsxyz/suzuka-full-node-setup:${CONTAINER_REV}
    container_name: setup
    environment:
      DOT_MOVEMENT_PATH: /.movement
      CELESTIA_RPC_CONNECTION_HOSTNAME: ${CELESTIA_RPC_CONNECTION_HOSTNAME:?CELESTIA_RPC_CONNECTION_HOSTNAME is not set}
      CELESTIA_RPC_CONNECTION_PORT: ${CELESTIA_RPC_CONNECTION_PORT:?CELESTIA_RPC_CONNECTION_HOSTNAME is not set}
      CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME: ${CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME:?CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME is not set}
      CELESTIA_WEBSOCKET_CONNECTION_PORT: ${CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME:?CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: m1-da-light-node
      MAPTOS_API_CONNECTION_HOSTNAME: suzuka-full-node
      FAUCET_API_CONNECTION_HOSTNAME: suzuka-faucet-service
      ETH_RPC_CONNECTION_HOSTNAME: ${ETH_RPC_CONNECTION_HOSTNAME}
      ETH_RPC_CONNECTION_PROTOCOL: ${ETH_RPC_CONNECTION_PROTOCOL}
      ETH_RPC_CONNECTION_PORT: ${ETH_RPC_CONNECTION_PORT}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    healthcheck:
      test: [ "CMD-SHELL", "ls" ]
      retries: 10
      interval: 10s
      timeout: 5s

  # underlying da light node runners should already be turned off

  # turn off suzuka-faucet-service
  suzuka-faucet-service:
    image: busybox
    container_name: suzuka-faucet-service
    command: sh -c 'echo "No setup type specified."'
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s