services:
  setup:
    image: ghcr.io/movementlabsxyz/suzuka-full-node-setup:${CONTAINER_REV}
    container_name: setup
    environment:
      DOT_MOVEMENT_PATH: /.movement
      # By default, all the listener hostnames and ports are reasonable.
      # However, for container networking, we need to specify the hostnames on the connection.
      # You can also use host.docker.internal for the host machine as all of these ports should be exposed.
      CELESTIA_RPC_CONNECTION_HOSTNAME: ${CELESTIA_RPC_CONNECTION_HOSTNAME:?CELESTIA_RPC_CONNECTION_HOSTNAME is not set}
      CELESTIA_RPC_CONNECTION_PORT: ${CELESTIA_RPC_CONNECTION_PORT:?CELESTIA_RPC_CONNECTION_HOSTNAME is not set}
      CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME: ${CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME:?CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME is not set}
      CELESTIA_WEBSOCKET_CONNECTION_PORT: ${CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME:?CELESTIA_WEBSOCKET_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: m1-da-light-node
      MAPTOS_API_CONNECTION_HOSTNAME: suzuka-full-node
      FAUCET_API_CONNECTION_HOSTNAME: suzuka-faucet-service
      ETH_RPC_CONNECTION_HOSTNAME: ${ETH_RPC_CONNECTION_HOSTNAME}
      ETH_RPC_CONNECTION_PROTOCOL: ${ETH_RPC_CONNECTION_PROTOCOL}
      ETH_RPC_CONNECTION_PORT: ${ETH_RPC_CONNECTION_PORT}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    healthcheck:
      test: [ "CMD-SHELL", "ls" ]
      retries: 10
      interval: 10s
      timeout: 5s