[package]
name = "bridge-e2e-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
keccak-hash = { workspace = true }

alloy-primitives = { workspace = true }

bridge-shared = { workspace = true }
ethereum-bridge = { workspace = true }

[lints]
workspace = true
