version: "3"

processes:

  setup-follower:
    command: |
      echo {{.PC_REPLICA_NUM}}
      DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-${PC_REPLICA_NUM}
      suzuka-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"
    replicas: 2