version: "3"

environment:

processes:

  setup:
    command: |
      export MAYBE_DEPLOY_MCR=true
      suzuka-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 3
      exec:
        command: echo "true"