version: "3"

processes:

  setup-follower-1:
    command: |
      #!/bin/bash
      export MAYBE_RUN_LOCAL=false
      export MAYBE_DEPLOY_MCR=false
      export MAPTOS_API_LISTEN_PORT=31731
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-1
      suzuka-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"

  suzuka-full-follower-1:
    command: |
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-1
      suzuka-full-node
    depends_on:
      m1-da-light-node:
        condition: process_healthy
      setup-follower-2:
        condition: process_healthy
      suzuka-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:31731

  setup-follower-2:
    command: |
      #!/bin/bash
      export MAYBE_RUN_LOCAL=false
      export MAYBE_DEPLOY_MCR=false
      export MAPTOS_API_LISTEN_PORT=32731
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-2
      suzuka-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"

  suzuka-full-follower-2:
    command: |
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-2
      suzuka-full-node
    depends_on:
      m1-da-light-node:
        condition: process_healthy
      setup-follower-2:
        condition: process_healthy
      suzuka-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:32731