services:

  suzuka-indexer:
    image: ghcr.io/movementlabsxyz/suzuka-indexer:${CONTAINER_REV}
    container_name: suzuka-indexer
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - MAPTOS_INDEXER_GRPC_LISTEN_HOSTNAME=${MAPTOS_INDEXER_GRPC_LISTEN_HOSTNAME}
      - INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING=${INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING}
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    restart: on-failure:5

volumes:
  dot-movement:

