services:

  suzuka-indexer:
    image: ghcr.io/movementlabsxyz/suzuka-indexer:${CONTAINER_REV}
    container_name: suzuka-indexer
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING=postgresql://postgres:password@database:5432
      - MAPTOS_INDEXER_GRPC_LISTEN_HOSTNAME=${SUZUKA_NODE_IP}
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    extra_hosts:
        - "database:${POSTGRES_IP}"
    restart: on-failure:5

volumes:
  dot-movement:

